name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode secrets.properties
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MAPKIT_API_KEY: ${{ secrets.MAPKIT_API_KEY }}
      run: |
        echo API_KEY=\"$API_KEY\" >> ./secrets.properties
        echo MAPKIT_API_KEY=\"$MAPKIT_API_KEY\" >> ./secrets.properties
    
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
